### ISSUE TITLE
CME while iterating mobs

### ISSUE THREAD

**Issue by perronosaurio** [imDaniX/Dangerous-Caves-2#10]
![image](https://user-images.githubusercontent.com/27968093/79077830-18d7e580-7cd2-11ea-8f3d-b1ea33330d87.png)

I dont know why the plugin generates this error.

**Comment by imDaniX** [comment]
Thanks for the report. I will fix it as soon as I can.

**Comment by imDaniX** [comment]
Please try latest build from Actions tab. Re-open the issue if problem still persists.
