### ISSUE TITLE
CME while iterating mobs (again)

### ISSUE THREAD

**Issue by perronosaurio** [imDaniX/Dangerous-Caves-2#11]
![image](https://user-images.githubusercontent.com/27968093/79136265-b8eb4880-7d7e-11ea-8978-d5b375541f8a.png)

**Comment by imDaniX** [comment]
Still persists, huh. Okay, thank you.

**Comment by imDaniX** [comment]
Please try latest build. Will remain this issue open until fix.

**Comment by perronosaurio** [comment]
@imDaniX it seems fixed, but the mob spawn ratio is more now for some reason

**Comment by imDaniX** [comment]
I don't think that it's related to DC. Plugin's spawn-rate is based on vanilla spawning - every time when server tries to spawn a mob, DC decides to spawn it's own(see mobs.try-chance) instead if old one.
Maybe the problem itself is related to the fact that DC mobs are *possibly* unable to despawn... I will change it in the next update.
