### ISSUE TITLE
Mining Fatigue even when it's not hot

### ISSUE THREAD

**Issue by xQuiller** [imDaniX/Dangerous-Caves-2#13]
Hey! So I like your plugin, but when I try to mine like close to water or something, even when it's not hot like in a wall in a mountain I get mining fatigue, and the cooldown itens dont work, like I get mining fatigue when I have an Ice on my inventory or a bucket with water, and this is really annoying, cause this plugins is really good!

**Comment by imDaniX** [comment]
Thanks for the report. I'll look into it, but I recommend you to just disable Depth Temperature. This mechanic is too shallow for now - it's just random fatigue effect giving. I'm going to upgrade it - temperature accumulation depended on player's depth and biome, cold-items consuming, maybe something more.

**Comment by xQuiller** [comment]
So how can I disable this? can you help me?

**Comment by imDaniX** [comment]
Just set its chance to 0 and use /dcaves reload.

**Comment by xQuiller** [comment]
so it's not working, I set the chance to 0 and I use /dcaves reload but I'm still with Fatigue and Slowness

**Comment by imDaniX** [comment]
What version of plugin do you use?

**Comment by xQuiller** [comment]
2.1.5, I think thats the last one, right?

**Comment by imDaniX** [comment]
Oh, this one. It's buggy, and latest release is 2.1.6. You can download it from [spigotmc](https://www.spigotmc.org/resources/dangerous-caves-2-make-your-caves-scary-1-12-2-1-15-2.76212/) page. Latest build from Actions tab is equal to it.

**Comment by xQuiller** [comment]
Ok! Now it's working fine, thankssss!

**Comment by imDaniX** [comment]
Good. Please reopen the issue if you will notice any related bugs with Temperature.
