### ISSUE TITLE
ERROR [PaperSpigot 1.15.2] Can anyone help me with this?

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [imDaniX/Dangerous-Caves-2#17]
https://pastebin.com/nuDfg03q

my console is spamming this error

**Comment by imDaniX** [comment]
Please update your config, especially Hypoxia section. Here's all you need - [config.yml](https://gist.github.com/imDaniX/fb2cad7bfeb57960bf4dc2ae19bbc96f/revisions).
