### ISSUE TITLE
Server stops responding

### ISSUE THREAD

**Issue by timvyxo** [imDaniX/Dangerous-Caves-2#18]
20.05 00:30:32 [Server] ERROR Current Thread: Server thread
20.05 00:30:32 [Server] ERROR PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
20.05 00:30:32 [Server] ERROR Stack:
20.05 00:30:32 [Server] ERROR sun.misc.Unsafe.park(Native Method)
20.05 00:30:32 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.defaults.BouldersGroup.generate(BouldersGroup.java:59)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.updateAdjacentComparators(World.java:1544)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.TileEntity.update(TileEntity.java:148)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockEntityState.update(CraftBlockEntityState.java:148)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockState.update(CraftBlockState.java:171)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlockState.update(CraftBlockState.java:166)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.decideBlock(BuildingsGroup.java:199)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generateStructure(BuildingsGroup.java:118)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generate(BuildingsGroup.java:105)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:32 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.defaults.TrapsGroup.generate(TrapsGroup.java:98)
20.05 00:30:32 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:611)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164)
20.05 00:30:32 [Server] ERROR net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
20.05 00:30:32 [Server] ERROR java.lang.Thread.run(Thread.java:748)
20.05 00:30:32 [Server] ERROR ------------------------------
20.05 00:30:32 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
20.05 00:30:32 [Server] ERROR ------------------------------
20.05 00:30:37 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-301 (MC: 1.15.2) ---
20.05 00:30:37 [Server] ERROR The server has not responded for 15 seconds! Creating thread dump
20.05 00:30:37 [Server] ERROR ------------------------------
20.05 00:30:37 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
20.05 00:30:37 [Server] ERROR Chunk wait task info below: 
20.05 00:30:37 [Server] ERROR 1270,-451 in 'world:
20.05 00:30:37 [Server] ERROR Load Task - none
20.05 00:30:37 [Server] ERROR Save Task - none
20.05 00:30:37 [Server] ERROR Chunk Holder - non-null
20.05 00:30:37 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:37 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:37 [Server] ERROR 1272,-463 in 'world:
20.05 00:30:37 [Server] ERROR Load Task - none
20.05 00:30:37 [Server] ERROR Save Task - none
20.05 00:30:37 [Server] ERROR Chunk Holder - non-null
20.05 00:30:37 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:37 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:37 [Server] ERROR 1259,-452 in 'world:
20.05 00:30:37 [Server] ERROR Load Task - none
20.05 00:30:37 [Server] ERROR Save Task - none
20.05 00:30:37 [Server] ERROR Chunk Holder - non-null
20.05 00:30:37 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:37 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:37 [Server] ERROR 1259,-459 in 'world:
20.05 00:30:37 [Server] ERROR Load Task - none
20.05 00:30:37 [Server] ERROR Save Task - none
20.05 00:30:37 [Server] ERROR Chunk Holder - non-null
20.05 00:30:37 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:37 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:37 [Server] ERROR 1257,-457 in 'world:
20.05 00:30:37 [Server] ERROR Load Task - none
20.05 00:30:37 [Server] ERROR Save Task - none
20.05 00:30:37 [Server] ERROR Chunk Holder - non-null
20.05 00:30:37 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:37 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:37 [Server] ERROR ------------------------------
20.05 00:30:37 [Server] ERROR Current Thread: Server thread
20.05 00:30:37 [Server] ERROR PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
20.05 00:30:37 [Server] ERROR Stack:
20.05 00:30:37 [Server] ERROR sun.misc.Unsafe.park(Native Method)
20.05 00:30:37 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generate(BuildingsGroup.java:74)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.defaults.PillarsGroup.generate(PillarsGroup.java:62)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:37 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.defaults.BouldersGroup.generate(BouldersGroup.java:59)
20.05 00:30:37 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:37 [Server] ERROR net.minecraft.server.v1_15_R1.World.updateAdjacentComparators(World.java:1544)
20.05 00:30:42 [Multicraft] Skipped 40 lines due to rate limit (100/s)
20.05 00:30:42 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-301 (MC: 1.15.2) ---
20.05 00:30:42 [Server] ERROR The server has not responded for 20 seconds! Creating thread dump
20.05 00:30:42 [Server] ERROR ------------------------------
20.05 00:30:42 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
20.05 00:30:42 [Server] ERROR Chunk wait task info below: 
20.05 00:30:42 [Server] ERROR 1265,-449 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:42 [Server] ERROR 1270,-451 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:light
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:features
20.05 00:30:42 [Server] ERROR 1272,-463 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:full
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:full
20.05 00:30:42 [Server] ERROR 1259,-452 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:full
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:full
20.05 00:30:42 [Server] ERROR 1259,-459 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:full
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:full
20.05 00:30:42 [Server] ERROR 1257,-457 in 'world:
20.05 00:30:42 [Server] ERROR Load Task - none
20.05 00:30:42 [Server] ERROR Save Task - none
20.05 00:30:42 [Server] ERROR Chunk Holder - non-null
20.05 00:30:42 [Server] ERROR Chunk Status - minecraft:full
20.05 00:30:42 [Server] ERROR Chunk Holder Status - minecraft:full
20.05 00:30:42 [Server] ERROR ------------------------------
20.05 00:30:42 [Server] ERROR Current Thread: Server thread
20.05 00:30:42 [Server] ERROR PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
20.05 00:30:42 [Server] ERROR Stack:
20.05 00:30:42 [Server] ERROR sun.misc.Unsafe.park(Native Method)
20.05 00:30:42 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.bl(IAsyncTaskHandler.java:131)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:120)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.decideBlock(BuildingsGroup.java:126)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generateStructure(BuildingsGroup.java:118)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generate(BuildingsGroup.java:60)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.defaults.BuildingsGroup.generate(BuildingsGroup.java:74)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1084)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:489)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:331)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:276)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.World.getType(World.java:664)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:194)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setBlockData(CraftBlock.java:177)
20.05 00:30:42 [Server] ERROR org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.setType(CraftBlock.java:166)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.StructureGroup.setType(StructureGroup.java:65)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.defaults.PillarsGroup.generate(PillarsGroup.java:62)
20.05 00:30:42 [Server] ERROR me.imdanix.caves.generator.CaveGenerator.populate(CaveGenerator.java:107)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:872)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$11(PlayerChunk.java:698)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunk$$Lambda$3631/1344153220.run(Unknown Source)
20.05 00:30:42 [Server] ERROR net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:118)

**Comment by imDaniX** [comment]
What's your server core and plugin version?

**Comment by imDaniX** [comment]
Accidentally closed the issue, sorry. Please try latest build.

**Comment by imDaniX** [comment]
Closed due to inactivity.
