### ISSUE TITLE
Unknown lag from DC2 (again)

### ISSUE THREAD

**Issue by plebexer** [imDaniX/Dangerous-Caves-2#20]
hey!, the plugin has been working good until today, with 50 players, with no reason tps dropped to 13, when it was not like this before, and now its happening again, i opened timings report and dangerouscaves is at the top, https://timings.aikar.co/?id=68d2fafdacd94b66867c7e631ff4fd6c#plugins

**Comment by imDaniX** [comment]
I don't see anything really related to DC2 in your timings. If you really think that DC is causing this problem - please try [spark](https://www.spigotmc.org/resources/spark.57242/) plugin.

**Comment by imDaniX** [comment]
Closed due to inactivity.
