### ISSUE TITLE
Disable Cave Aging Inside Claims

### ISSUE THREAD

**Issue by HyperVx2** [imDaniX/Dangerous-Caves-2#21]
My players would love to make their bases underground without the cave aging feature inside their claims. Is it possible to hook with GriefPrevention to stop cave aging inside claims?

**Comment by imDaniX** [comment]
I just tried to add GriefPreventionFlags support into the plugin in latest build. Honestly I'm not sure if it works and persists after restart, but would be awesome if you try it.
If you don't want to use another plugin - I'm planning to add flag-less mode, so it will just disable certain features inside of regions.

**Comment by HyperVx2** [comment]
Thank you. I'll give it a try soon and will give feedback.

**Comment by imDaniX** [comment]
Added flagless mode, so you can choose it to disable some of features inside of claims.
`worldguard-flagless` for WorldGuard and `griefprevention-flagless` for GriefPrevention.

**Comment by LoneDev6** [comment]
"[DangerousCaves] Can't find mode "griefprevention". Regions feature is disabled."

**Comment by imDaniX** [comment]
@LoneDev6 You have to use `griefprevention-flagless` for just GriefPrevention. Anyway, I will look into it. 
I was already thinking about combined protections. It's actually quite to do simple with current system. Will try to implement it.

**Comment by LoneDev6** [comment]
Thanks please let me know.
Anyway I triesd also to use griefprevention-flagless without success, as I said

**Comment by imDaniX** [comment]
@LoneDev6 GP region checker should work properly now. Also renamed `griefprevention` mode to `griefprevention-flags` and `griefprevention-flagless` to `griefprevention` (and same for WG).
Also you can now specify multiple modes, like `mode: griefprevention,worldguard`

**Comment by niqoar** [comment]
It continues to happen with Dangerous-Caves-2 2.2.7 and GriefPrevention 16.14.0 :(

**Comment by niqoar** [comment]
This continues to happen in griefprevention protections :(

**Comment by imDaniX** [comment]
@niqoar, can you show list of your modes from the config?

**Comment by niqoar** [comment]
> @niqoar, can you show list of your modes from the config?

Yes, this is my config: https://pastebin.com/vCEENGVm

**Comment by imDaniX** [comment]
@niqoar, as for now not sure what's wrong. Will look deeper into it a bit later.

**Comment by imDaniX** [comment]
There was some commits related to this issue. If anyone is interested - please test it.

**Comment by l3st4tPlugins** [comment]
My players confirm that the cave aging is mostly gone - except for one thing: the mushrooms.

**Comment by imDaniX** [comment]
@l3st4tPlugins are you sure that DC causes it and not vanilla mushrooms spreading?

**Comment by l3st4tPlugins** [comment]
Not sure. Didn't even know vanilla mushrooms can spread. I guess I could add debug and monitor it.

**Comment by l3st4tPlugins** [comment]
After testing, there were some hidden mushrooms in their lands, and removing them fixed it. So at least under the Lands protection, cave aging inside claims is disabled.

**Comment by imDaniX** [comment]
Will leave this issue open for one more month just in case.

**Comment by Kenaestic** [comment]
Hi. I'm not sure if this is related to the problem above but I'm getting this  warning from the plugin:

> [08:19:23 WARN]: [DangerousCaves] Can't find mode "griefprevention".

I also have the same problem as the person above.

**Comment by imDaniX** [comment]
@Kenaestic It tells that DC2 can't detect GriefPrevention plugin on your server, so mode can't be used - do you actually have GriefPrevention installed? Also, what's your exact second problem?

**Comment by Kenaestic** [comment]
> 
> 
> @Kenaestic It tells that DC2 can't detect GriefPrevention plugin on your server, so mode can't be used - do you actually have GriefPrevention installed? Also, what's your exact second problem?

Yes I'm positive. I also have other plugins hooking into griefprevention like dynmap. I'm on the newest version on both Dangerous Caves and Griefprevention. I tried downgrading versions with both plugins without succes. I suspect it may be a paper update that caused this but I'll have to test it out.

I left my server startup log in the spigot discussion thread but I'll send you an up-to-date one here: 
https://pastebin.pl/view/0034cc76

DC settings:
https://pastebin.pl/view/bbb04e8f

Griefprevention settings:
https://pastebin.pl/view/4f2393d7

Let me know if you need anything else.

**Comment by imDaniX** [comment]
@Kenaestic Seems like somehow DC starts sooner than GP, and that's quite weird.

**Comment by imDaniX** [comment]
@Kenaestic Please try latest build, it should be fine now.

**Comment by Kenaestic** [comment]
> 
> 
> @Kenaestic Please try latest build, it should be fine now.

Do you have a link where I can download it?

**Comment by Kenaestic** [comment]
> 
> 
> @Kenaestic Please try latest build, it should be fine now.

I can confirm that I'm not getting any warnings now. I'll test the plugin further and will report back if there's any problems. Thanks for your help 👍

**Comment by imDaniX** [comment]
Please reopen the issue if something is still doesn't work.
