### ISSUE TITLE
[1.16.x] Weird spawn behaviour on Paper server

### ISSUE THREAD

**Issue by Tikkle** [imDaniX/Dangerous-Caves-2#23]
**Describe the bug**
Mobs seem to be spawning in the walls in the caves.

**Screenshots or logs**
No logs/errors generated.
[video](https://youtu.be/plteCs5CUto)

**Additional information**
- Server version: [version](https://gyazo.com/6ab2ca0828be5271608439e49b4e32ac)
- Plugin version: v2.2.6 c18
- Paperspigot
- Plugins list provided in video.

**Comment by imDaniX** [comment]
Thank you for tgw report. That's quite strange behaviour, because mobs are spawned only when and where vanilla mobs are spawning. Maybe it's related to paper 1.16 - I'm using optimized PreCreatureSpawnEvent from there, and maybe something goes wrong.
If possible - please test it on spigot. I will do it myself later, but it's good to have some more data.

**Comment by Tikkle** [comment]
It seems to be okay on Spigot [version](https://gyazo.com/0a80a025210ab586c32d96ed1718366d)

**Comment by imDaniX** [comment]
Alrighty. Will test what's wrong with paper's spawning and will create an issue on their GitHub repo. As for now - will keep this issue open to except any duplicated issues.

**Comment by frogglen** [comment]
hi, i am using the latest version Dangerous-Caves-2.2.7-SNAPSHOT and i am having the same problem the custom mobs spawn on walls and suffocate.
I am using the latest version of paper 1.16.1 and I have also seen normal mobs spawning on the walls when dangerous-caves is activated.

**Comment by imDaniX** [comment]
@frogglen As I said, it's not DC bug - it's Paper bug. As temporary solution in latest snapshots I added option `mobs.use-prespawn`. If you're using 1.16.1 paper - set it to false.

**Comment by imDaniX** [comment]
Current behaviour of PreCreatureSpawnEvent is expected as for 1.16. I guess current workaround is the only way to implement spawning, so I'll leave it like this.
