### ISSUE TITLE
Mobs spawn in water, sees and ocean massivly

### ISSUE THREAD

**Issue by CloudeLecaw** [imDaniX/Dangerous-Caves-2#24]
On our server the monster spawn massive on water (speciyl on the water ground) try to go up and die..as result tons of items aare spread over the seas and oceans

if there a change to prevent spawning of the Dangerous Cave mobs in any kind of Waterblocks?
It does not make sens so have them in seas, oceans, lakes...   etc..

Server. paper-79
Dangerous Caves 2 - v2.2.6

i looked at the update of 2.2.7 but i see no adding of some prevention like this, so i assume this issues stil exists

**Comment by imDaniX** [comment]
Related to Paper prespawn behavior https://github.com/imDaniX/Dangerous-Caves-2/issues/23
