### ISSUE TITLE
Cannot fully disable cave aging

### ISSUE THREAD

**Issue by JuanDelPueblo** [imDaniX/Dangerous-Caves-2#25]
**Describe the bug**
When either `worlds:` or `replace-blocks:` in `caverns.aging:` is set to blank or to [], I get an enable error as seen below. It used to not error in the previous version 2.2.6. I have already set other values like max-y to 0, but I will have better peace of mind if it can be set to blank or have a toggle for the feature.

**Screenshots or logs**
https://hastebin.com/opiraduqaj.bash

**Additional information**
- Server version = Paper-79 (MC: 1.16.1)
- Plugin version = 2.2.7

**Comment by imDaniX** [comment]
To disable features just set its chance to 0. This is already mentioned in config comments, but seems like it's not that obvious, so I will add `enable` option for each feature later.

**Comment by JuanDelPueblo** [comment]
Thanks for adding an idiot-proof option to enable/disable features, I'll close this now

**Comment by imDaniX** [comment]
Wrong issue num, related to #21*
