### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by niqoar** [imDaniX/Dangerous-Caves-2#26]
**Describe the lag**
The server stopped responding and crashed.

**Log**
https://pastebin.com/n8ezZD0v

**Additional information**
- git-Tuinity-"9046061" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
- DangerousCaves v2.2.7 c19

**Comment by imDaniX** [comment]
Increase your `caverns.aging.schedule-timer` up to 20.
