### ISSUE TITLE
Priority 0 doesn't work for mobs

### ISSUE THREAD

**Issue by IsXGeo** [imDaniX/Dangerous-Caves-2#27]
I would like to request the ability to disable different parts of the plugin, for instance I would like to disable hypoxia and the custom mobs and only have cave-ins and cave aging enabled. Ive tried modifying the priority and chance values however a few mobs such as the hungering darkness and such still seem to spawn occasionally.

**Comment by imDaniX** [comment]
Please, read the conifg. All the features, including hypoxia, can be disabled by setting its value to 0.
Mobs also can't spawn if their priority is 0. I think the thing is that you saw already spawned mobs. You can kill these using command `/dc kill mob-type` where `mob-type` is type from the config.

**Comment by IsXGeo** [comment]
This is what I did. I set all the mobs to have a priority of zero however a few of them, not all, still seemed to spawn. This included the hungering darkness. I did indeed use /dc kill to kill all mobs.

**Comment by imDaniX** [comment]
Will look into it later. Sorry, I'm kinda busy right now, so I can't check it yet.

**Comment by imDaniX** [comment]
So.. if it was a thing one the first place, it should be already fixed. If it still doesn't work - please reopen the issue.
