### ISSUE TITLE
Add Lands to softdepends

### ISSUE THREAD

**Issue by l3st4tPlugins** [imDaniX/Dangerous-Caves-2#30]
**Describe the bug**
Lands might load after DangerousCaves because I forgot to add it to softdepends on plugin.yml. Instead of making a PR for something this small, I decided to make it an issue.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem. For logs please use [pastebin](https://pastebin.com/), [hastebin](https://hasteb.in/) or something alike. 
Not applicable.

**Additional information**
- Server version (/version)
- Plugin version (/dcaves)
- Server core name (Spigot, Paper etc.)
- Plugins list (if possible)
Not applicable.

**Comment by imDaniX** [comment]
Will delay next release until https://github.com/imDaniX/Dangerous-Caves-2/tree/papi got finished.
