### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by EliteAspect21** [imDaniX/Dangerous-Caves-2#31]
**Describe the bug**
I will try to spawn in a mob using /dcaves summon <mob>, but the mob always despawns after less than a second. The sounds and aging still work fine

**Screenshots or logs**
N/A

**Additional information**
- Server version: 1.16.1-R0.1-SNAPSHOT
- Plugin version: v2.2.9 c20
- Server core name: Spigot / CraftBucket
- Plugins list:
![image](https://user-images.githubusercontent.com/47304559/90555542-23f9c100-e15d-11ea-90f5-8aaa614400e9.png)

**Comment by EliteAspect21** [comment]
Also, magma creepers don't do anything. They just spawn particles

**Comment by imDaniX** [comment]
I have checked both, and it works just fine. So, I can't confirm the issue. Might be something related to your plugins (some core plugins like FogusCore theoretically interrupt mobs processing, but I really don't know)
![2020-08-19_06 35 11](https://user-images.githubusercontent.com/18292506/90589472-d4f86e00-e1e6-11ea-9cd6-b78c88ffa057.png)
Will leave this issue open, maybe some users have this problem too.

**Comment by EliteAspect21** [comment]
I will see if I can record it

**Comment by imDaniX** [comment]
Closed due to inactivity.
