### ISSUE TITLE
Depth Hypoxia - Actionbar no work?

### ISSUE THREAD

**Issue by niqoar** [imDaniX/Dangerous-Caves-2#32]
**Describe the bug**
I have actionbar true in hypoxia options, but chat still used.

**Screenshots or logs**
Image: https://i.imgur.com/2pZ35UC.png
Config: https://pastebin.com/ttkC0cDx

**Additional information**
Tuinity version git-Tuinity-"0b86de3" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
DangerousCaves v2.2.10 c21

**Comment by imDaniX** [comment]
Should be fixed now. Please try latest dev-build.
