### ISSUE TITLE
World generation causes crash with ItemsAdder installed

### ISSUE THREAD

**Issue by LoneDev6** [imDaniX/Dangerous-Caves-2#36]
**Describe the bug**
Seems the plugin is causing a server crash whenever a Tree spawned with my plugin ItemsAdder is spawned at the same place where a chest spawned by Dangerous Caves is spawned and filled.

**Screenshots or logs**
Here's an issue about that: https://github.com/LoneDev6/ItemsAdder/issues/452
I'm 90% sure I'm not accessing that block async while spawning the tree.
This is my solution: 
> Seems this plugin is accessing my trees blocks on generation in an asynchronous way which is not good.
You should ask DangerousCaves author about that.
If they are accessing the block in a sync way let them know to just add a try and catch of type java.lang.IllegalStateException here:
https://github.com/imDaniX/Dangerous-Caves-2/blob/89f3d466fd5c2a5dadefb7e20001a39c78d12a9a/DangerousCaves/src/main/java/me/imdanix/caves/generator/AbstractStructure.java#L67

**Comment by imDaniX** [comment]
The thing is that it isn't used unless chunk is being generated right now. You see, it comes from CaveGenerator#populate, which is called just on every chunk generation...
Current generator is just a legacy mess already, so I think it won't get any worse with this workaround. I'm going to rewrite the whole system anyway.

**Comment by Fargus5** [comment]
Thanks so mutch, please let we know.

**Comment by imDaniX** [comment]
@Fargus5 You can try latest dev-build, workaround is already used there.
