### ISSUE TITLE
Elite Mobs Compatibility 

### ISSUE THREAD

**Issue by DocGoose49** [imDaniX/Dangerous-Caves-2#40]
This plugin is great and I would use it for my server but.. theres one problem. I use a plugin called Elite Mobs and the original dangerous caves wouldn't work with the plugin because it changed Elite Mob's damage system to their format which messed up some stuff for the plugin. I would like to know if this has compat with it or if you can make Compatibility with the mod.

**Comment by imDaniX** [comment]
Please be more precise - what do you mean by "compatibility"?
Elite Mobs already provides compatibility option in its configuration file - see #6

**Comment by imDaniX** [comment]
Closed due to inactivity.
