### ISSUE TITLE
Error in enabling plugin on the latest paper

### ISSUE THREAD

**Issue by yebanme** [imDaniX/Dangerous-Caves-2#41]
**Describe the bug**
The plugin fails to start normally when the server starts

**Screenshots or logs**
[This is the output error message](https://pastebin.com/RpPZ4uLJ)

**Additional information**
- Server version Paper-487 (MC: 1.16.5)
- Plugin version Dangerous-Caves-2.2.14-SNAPSHOT  latest version
- Server core name Paper 
- Plugins list Plugins (1): DangerousCaves

**Comment by imDaniX** [comment]
Thank you for the report. Should be resolved now.
