### ISSUE TITLE
MythicMobs Compatibility

### ISSUE THREAD

**Issue by Keopsfenks** [imDaniX/Dangerous-Caves-2#42]
Hi, before we begin, I'd like to say it's a really successful plugin. Congratulations.

To get to the point, I don't know if MythicMobs supports it, but. Does the DC plugin support the MyhicMobs plugin?

Can I use MM mobs in short.

**Comment by imDaniX** [comment]
It's fine to use both at the same time. The only thing that may conflict is probabilities of mobs spawning if you're using vanilla spawning in MM, but it's really minor problem - one of plugins sometimes will override other's mobs, but I don't think you'll notice an actual difference.

**Comment by Keopsfenks** [comment]
I get it, thank you. 

but instead of the mobs that are already in place, we can add mobs that we've created ourselves.

config file, for example:

mm-mobs-name: SkeletonKing

or if it is more than one 

mm-mobs-name: "SkeletonKing", "ZombieKinh", "Trial-boss"

and so on

**Comment by imDaniX** [comment]
Sorry, I didn't get it. Do you mean, you want to spawn MM mobs through DC? If so - I don't think that's a good idea, just because MM is much better in the aspect of spawning configuration. Or you want to fully replace all the vanilla mobs with MM, but still want to replace some mobs by DC's mobs?

**Comment by Keopsfenks** [comment]
There has to be more mobs that we can add, and I agree with that "but still want to replace some mobs by DC's mobs?"

**Comment by imDaniX** [comment]
Well, I don't know what priority MM is using. I would assume that it's HIGHEST, while DC uses HIGH - it means that DC will try to spawns its mobs first; if it fails - then MM will try to spawn those; if it fails - vanilla mob will be spawned. So, it really depends on MM's internal priority.
Anyway, I don't think you will have any problems with DC+MM, and if you'll see any - just report it, and I'll try to help you.
