### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by loothillRw** [imDaniX/Dangerous-Caves-2#43]
**Describe the bug**
I actually set Cave Golem priority to 0 (wich should be disabled as mentioned in the config)
but this one still spawns while mining

**Plugin config**
https://pastebin.com/mDWppWge

**Server Info/Plugin**
- Server version 1.16.5
- Plugin version v2.2.13 c24
- Server Yatopia

**Comment by imDaniX** [comment]
Intented. Set `spawn-from-block` to 0 too.
