### ISSUE TITLE
DC2 not working

### ISSUE THREAD

**Issue by DSJZ** [imDaniX/Dangerous-Caves-2#44]
DC2 not working on my severs, mobs not spawning, no structures, cave aging is also not present. Do i need to install another plugin?

**Comment by imDaniX** [comment]
No, it should work as-is. Does /dcaves command works? If doesn't - please send your start-up log(until "Done" message) and send it with https://hatebin.com/

**Comment by DSJZ** [comment]
> No, it should work as-is. Does /dcaves command works? If doesn't - please send your start-up log(until "Done" message) and send it with https://hatebin.com/

Ok, so the command works, but nothing spawns naturally. I even remove all plugins except for DC2 still didnt work. Things arent spawning naturally. All vanilla mobs, no cave aging. Etc.

**Comment by DSJZ** [comment]
https://hatebin.com/qybozsfakk

**Comment by imDaniX** [comment]
Ah, I get it. Your world name is different. Every feature contains the `worlds` section - you should make it empty or replace `world` name with your world name.
So
```yaml
worlds:
  - world
```
should become
```yaml
worlds:
  - Salakkau
```
Replace it in every feature section.

Also, next time please use bug-report template.

**Comment by DSJZ** [comment]
> Ah, I get it. Your world name is different. Every feature contains the `worlds` section - you should make it empty or replace `world` with your overworld world name.
> So
> 
> ```yaml
> worlds:
>   - world
> ```
> 
> should become
> 
> ```yaml
> worlds:
>   - Salakkau
> ```
> 
> Replace it in every feature section.
> 
> Also, next time please use bug-report template.

Ah okay, my bad. I thought i didnt need to change that. Thank you 🙏🏻

**Comment by imDaniX** [comment]
Glad to hear it helped you.
