### ISSUE TITLE
Make Aging ignore lit blocks

### ISSUE THREAD

**Issue by pupshadow** [imDaniX/Dangerous-Caves-2#46]
Is there a way to make it so cave aging only happens to caves that has low light levels instead of cave built by players that have torches in it?

**Comment by imDaniX** [comment]
Sorry for a late response. Just use `caverns.aging.max-light-level` option. 0 disables light check.

**Comment by pupshadow** [comment]
What do you suggest a good number for this would be? I thought that was it but didn't fully understand it lol. Thankyou for the response its alright its not much of a big deal just a nice t o have lol.

**Comment by imDaniX** [comment]
Well, if you want the Aging to avoid any light - set it to 1.

**Comment by pupshadow** [comment]
Thank you for the help and explanation of what the max light level meant.
