### ISSUE TITLE
Vexed Armor - How to take the armor off

### ISSUE THREAD

**Issue by Ian1547** [imDaniX/Dangerous-Caves-2#48]
This is not a bug in a game unless it is but I was attacking a vexed armor and it switched my armor to the armor it was wearing, but I cannot take the armor off unless I swap into creative mode. Is there a way to remove the armor? Thank you.

**Comment by imDaniX** [comment]
Hexed armor uses vanilla's "curse of binding" enchantment. So, to take the armor off, well, you need to die.
