### ISSUE TITLE
MythicMobs Support - Suggestion

### ISSUE THREAD

**Issue by Fantom250YT** [imDaniX/Dangerous-Caves-2#49]
It would be cool to have some sort of MythicMobs support allowing people to create their own mobs into the game.

MythicMobs - https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/

Hopefully this can be a feature in the future!

**Comment by imDaniX** [comment]
MysticMobs already has **highly** configurable spawning options - I'm not sure if I can add something more to it?
