### ISSUE TITLE
Not actually sure it's doing anything

### ISSUE THREAD

**Issue by HeavyMetalJesus** [imDaniX/Dangerous-Caves-2#51]
This might be a very stupid question and I'm sorry if this isn't the right place. I've had it active for some time now, but don't know if it's working. Is there a way to check this? Total noob at this stuff. 

Spigot 1.17. Latest plug-in build.

**Comment by HeavyMetalJesus** [comment]
Sorry. That should be PaperMC 1.17...

**Comment by imDaniX** [comment]
Well, first of all, check if the plugin is shown green in the /plugins list. If it is - try to spawn a mob. You may try and increase caves aging chances, then reload the plugin and use `/dcaves tick` command (please, don't try it on a production server - that's generally a bad idea)
