### ISSUE TITLE
Health must be between 0 and 30.0, but was 39.0. Incompatibility with a mob levelling plugin (?)

### ISSUE THREAD

**Issue by CrispyDairy** [imDaniX/Dangerous-Caves-2#53]
**Describe the bug**
I have a plugin that makes mobs more difficult the further out you go in the world. And it increases the mob's health.
**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem. For logs please use [pastebin](https://pastebin.com/), [hastebin](https://hasteb.in/) or something alike.

**Plugin config**
Add a config here. Please use [pastebin](https://pastebin.com/), [hastebin](https://hasteb.in/) or something alike.

**Additional information**
- Server version (/version)
- Previous version: git-Purpur-1330 (MC: 1.17.1)
- Plugin version (/dcaves)
- DangerousCaves v2.2.13 c24
- Server core name (Spigot, Paper etc.)
- Purpur
- Plugins list (if possible)
- The plugin is "levelled mobs"

**Comment by imDaniX** [comment]
Please, provide more info - config and log files. Use [pastebin](https://pastebin.com/), [hastebin](https://hasteb.in/) or something alike.

**Comment by imDaniX** [comment]
Actually, consider updating your LevelledMobs plugin. It got updated recently and now has an option to disable leveling DC mobs.
