### ISSUE TITLE
Console tells all kills

### ISSUE THREAD

**Issue by CloudeLecaw** [imDaniX/Dangerous-Caves-2#56]
**Describe the bug**
The console tell you about each dangours mob that is killed. Any chance you can disable this?

**Screenshots or logs**
![Screenshot_20210901-162305](https://user-images.githubusercontent.com/12080017/131690090-449b9c95-2ad7-4b22-9756-acf1d2cbdd9e.png)

**Server version**
Paper 1.17.1

**Comment by imDaniX** [comment]
`log-named-deaths` in spigot.yml
