### ISSUE TITLE
Suggestion, Elitemobs support

### ISSUE THREAD

**Issue by oORevanOo** [imDaniX/Dangerous-Caves-2#59]
Hey there,

I use a Plugin called Elitemobs
Would It be possible to add a check to skip Mob conversion if that mob is already a Custom mob? (so if it has a Nametag, dangerous caves would skip it)

My problem is, that Dangerous Caves converts Mobs, which were created by Elitemobs, so they loose their powers, and get the ones by Dangerous Caves

I like to use both plugins aside, but it seems like its not possible for the Elitemobs dev to implement something to make Dangerous Caves compatible.
I think this is, because Dangerous Caves converts Mobs after they got an Elite. 

Would be Awesome if that would be possible, because your Plugin adds so much awesome stuff! 

Greetings from Germany

**Comment by oORevanOo** [comment]
Maybe you could add something like this in config: Clear all mob properties before the conversion, so if a mob had custom powers, stats or whatever, it would clear it and make it a 'fresh' Dangerous Caves mob 

Because right now, converted mobs that were an Elite before, are a mix of both Plugins when your plugin converts them

**Comment by imDaniX** [comment]
> Clear all mob properties before the conversion, so if a mob had custom powers, stats or whatever, it would clear it and make it a 'fresh' Dangerous Caves mob

In fact, DC2 already does that. Do you have the `enableHighCompatibilityMode` config option in EliteMobs enabled?

**Comment by oORevanOo** [comment]
No I don't 

I will do that right now!
Gonna reply soon

**Comment by oORevanOo** [comment]
Sir, I'll thank you for that! I totally forgot about this setting >.>

My bad
Awesome fast answer and fix! :)
