### ISSUE TITLE
Cave-ins duplication bug

### ISSUE THREAD

**Issue by memehacks64** [imDaniX/Dangerous-Caves-2#7]
![Base Profile Screenshot 2020 03 31 - 02 36 46 71](https://user-images.githubusercontent.com/21993804/78006929-db9b4d00-72fa-11ea-9158-4b626b39aad0.png)
i found this bug that actually is to op for any survival server, I was mining i mine rock and i get an explosion that make a big hole, so i continue mining i found diamond, i try to mine the diamond ore and i get another explosion that make another hole but also make a bis wall full of diamond ore.

**Comment by imDaniX** [comment]
Thanks for the report. I already know about this bug, but I can't fix it until 2.1.0 update. As temporary solution please disable `cave-ins` feature(set its `chance` to `0`)

**Comment by imDaniX** [comment]
Should be fixed now.
